Ability to patch JS/TS files (#version# template) and .net core csproj files
Rubius/VersionPatcher pull request #2
Opened 2017-12-31 10:10 UTC by Shaddix

2018-01-11 05:29 UTC, SemyonL requested changes

2018-01-11 05:29 UTC, SemyonL commented on BuildTask/VersionPatcher/patcher.ps1
> +		$firstPropertyGroup = $xml.Project.PropertyGroup;
А если версия будет не в первой PropertyGroup, а например во второй?
Лучше использовать XPath, чтобы наверняка проверить, что нет версии.

2018-01-11 05:29 UTC, SemyonL commented on BuildTask/VersionPatcher/task.json
> +  "id": "eb476c60-3c22-11e6-a55d-a780b9158b05",
А почему поменялся ID?

2018-05-24 09:07 UTC, Shaddix commented
fixed

2021-12-05 09:32 UTC, closed without merging